config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # title screen
  root 'title#index'
  post 'title/new_game'
  post 'title/continue_game'

  #root "markets#new"
  #get "markets", to: "markets#new"
  #  post "markets", to: "markets#create"

  #resources :games
  #resources :days

  resources :inventories
  resources :markets, only: %i[new create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# Base record class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
# Represents a single day in the game
class Day < ApplicationRecord
  belongs_to :game
  has_one :inventory
  has_one :market

  accepts_nested_attributes_for :inventory, :market

  # Will simulate a single day. Changes are committed to the database following the simulation.
  def simulate
    customer_count = people_passing_by
    raise GameOver, "You didn't have any customers." if customer_count.zero?

    inventory = InventoryInterface.new self.inventory
    lemonades = self.inventory.lemonades
    sold_lemonades = lemonades - people_passing_by

    # calculate the income from the lemonades
    income = sold_lemonades * lemonade_price

    # calculate the damage to the reputation
    if sold_lemonades.negative?
      reputation_hit = -sold_lemonades * 0.001
      self.reputation = reputation + reputation_hit
    end

    # remove the lemonades from the inventory
    self.inventory.cash = self.inventory.cash + income
    inventory.take_lemonade sold_lemonades
  end

  def people_passing_by
    temp_chance = 0.65 * ((temperature - 10) / 35) + 0.3
    temp_walkers = population * temp_chance

    walkers = temp_walkers * (1 - reputation.clamp(0, 1))
    walkers.floor.clamp(0, population)
  end

  class GameOver < StandardError; end

  private

  def end_of_day_reputation

  end

  def set_market_price

  end
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
end

app/models/inventory.rb
# frozen_string_literal: true

# Represents the players inventory
# Stores the players lemons, cash, sugar and lemonades.
class Inventory < ApplicationRecord
  belongs_to :day
end

app/models/market.rb
class Market < ApplicationRecord
  validates_inclusion_of :lemon_price, in: 0.25..0.5
  validates_inclusion_of :sugar_price, in: 0.02..0.05
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protected

  def game_session
    GameSessionStorage.get_game(session)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def new
    @inventory = Inventory.last
    render(locals: { inventory: Inventory.last })
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])
    inv = InventoryInterface.new(@inventory)
    val = params[:inventory][:lemonades].to_i
    inv.make_lemonade(val)
    redirect_to @inventory
  end
end

app/controllers/markets_controller.rb
class MarketsController < ActionController::Base
  attr_reader :market, :inventory

  def new
    @market = Market.new(lemon_price: rand(0.25..0.5).round(2), sugar_price: rand(0.02..0.05).round(2))
    @inventory = Inventory.create(lemons: 10, sugar: 10, cash: 20) # current_inventory

  end

  def create
    @market = Market.new(lemon_price: given_params[:lemon_price].to_f, sugar_price: given_params[:sugar_price].to_f)
    sale_service = SaleService.new(current_inventory, @market)
    success = sale_service.buy_goods(given_params[:new_lemons].to_i, given_params[:new_sugars].to_i)
    if success == 'Not enough funds'
      render :new, status: :unprocessable_entity, flash: { notice: 'Whoops something went wrong' }
    else
      render :show, status: :created, flash: { notice: 'Successfully bought items', location: Market.last }
    end
  end

  def show
    @market = Market.find(params[:id])
  end

  private

  def current_inventory
    require 'inventory'
    @inventory = Inventory.last
  end

  def given_params
    params.require(:market).permit(%i[lemon_price sugar_price new_lemons new_sugars])
  end
end

app/controllers/title_controller.rb
# frozen-string-literals: true

# Presents a title screen to the player and acts as our index page for new visitors.
class TitleController < ApplicationController
  def index
    @game = game_session
  end

  def new_game
    game = Game.new
    day = DayFactory.new_day(game)

    GameSessionStorage.set_game(session, Game.new)
    redirect_to_game
  end

  def continue_game
    redirect_to_game
  end

  private

  def redirect_to_game
    redirect_to markets_path  # TODO: switch over to the day view instead of markets
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# General application helpers
module ApplicationHelper
end

app/views/inventories/_form.html.erb
<%= form_with model: @inventory do |f| %>
  <%= f.label :lemonades %>
  <%= f.number_field :lemonades, value: 0 %>
  <%= f.submit "Make"%>
<% end %>

app/views/inventories/new.html.erb
<h1>Inventory</h1>

<h2> Cash: $<%= @inventory.cash.round(2)%> </h2>
<h2> Lemons: <%= @inventory.lemons%> </h2>
<h2> Sugar: <%= @inventory.sugar%> </h2>

<h2>Make Lemonade:</h2>
<div class="morning">
  <div class="settings">
    <table>
      <tr>
      <%= render partial: "form", locals: { inventory: @inventory } %>
      </tr>
    </table>
  </div>

  <h2> Lemonade for the day: <%= @inventory.lemonades%></h2>

  <footer>
    <%= link_to "Back to day", @day, class: "button" %> 
  </footer>
</div>

app/views/inventories/show.html.erb
<h1>Inventory</h1>

<h2> Cash: $<%= @inventory.cash.round(2)%> </h2>
<h2> Lemons: <%= @inventory.lemons%> </h2>
<h2> Sugar: <%= @inventory.sugar%> </h2>

<h2>Make Lemonade:</h2>
<div class="morning">
  <div class="settings">
    <table>
      <tr>
      <%= render partial: "form", locals: { inventory: @inventory } %>
      </tr>
    </table>
  </div>

  <h2> Lemonade for the day: <%= @inventory.lemonades%></h2>

  <footer>
    <%= link_to "Back to day", @day, class: "button" %> 
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LemonStand</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/new.html.erb
<h1>Market</h1>

<%= form_with(model: @market) do |f| %>
<div class="item-tiles container">
  <div class="item-tile">
    <table>
      <tr>
        <th>Lemon</th>
        <td><%= @market.lemon_price %></td>
      </tr>
      <tr>
        <td>In inventory:</td>
        <td><%= @inventory.lemons %></td>
      </tr>
    </table>
    <div class="buy-strip">
      <label>
        <span class="title">Buy</span>
        <%= f.label :new_lemons %>
        <%= f.number_field :new_lemons, value: 1 %>
      </label>
    </div>
  </div>
  <div class="item-tile">
    <table>
      <tr>
        <th>Sugar</th>
        <td><%= @market.sugar_price %></td>
      </tr>
      <tr>
        <td>In inventory:</td>
        <td><%= @inventory.sugar %></td>
      </tr>
    </table>
    <div class="buy-strip">
      <label>
        <span class="title">Buy</span>
        <%= f.label :new_sugars %>
        <%= f.number_field :new_sugars, value: 1 %>
      </label>
    </div>
  </div>
</div>

<div class="container wallet">
  <table>
    <tr>
      <th>Wallet</th>
      <td><%=@inventory.cash %></td>
    </tr>

  </table>
</div>
  <%= f.hidden_field :lemon_price, :value => @market.lemon_price %>
  <%= f.hidden_field :sugar_price, :value => @market.sugar_price  %>

<%= f.submit "Buy"%>

<% end %>

app/views/markets/show.html.erb
<%= flash[:notice] %>

<br>Lemon price: <%= @market.lemon_price %>
<br>Sugar price: <%= @market.sugar_price %>
<br>Remaining cash: <%= @inventory.cash %>

app/views/title/index.html.erb
<main class="title-menu">
  <header>
    Lemonade Stand Game
  </header>
  <div class="buttons">
    <%= link_to "New Game", title_new_game_path, method: :post, class: "button", data: { confirm: "Your progress will be lost. Are you sure?" } %>

    <% unless @game.nil? %>
      <%= link_to "Continue Game", title_continue_game_path, method: :post, class: "button" %>
    <% end %>
  </div>
</main>